UART: blocking read, async read and async write
InviNets/whip6-pub pull request #3
Opened 2017-02-14 20:18 UTC by IngaRueb

Changes:

- disable FIFO mode for UART (by moving the command UARTEnable before UARTFIFOEnable(false))

- wire blocking read, async write and async read to HalBlockingUART (need to rename this component in the future)

Additional applications test single functionalities (blocking and asynchronous reading and writing).

2017-02-21 16:14 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/BlockingUART0Pub.nc
> +    provides interface ReadNow<uint8_t>;
Zamieszczenie interfejsów asynchronicznych w konfiguracji o nazwie BlockingUART0Pub wydaje mi się trochę nieintuicyjne.

2017-02-21 16:43 UTC, IngaRueb commented
Oczywiście, nazwa jest tymczasowa
 Mam ją zmienić w oddzielnym commicie (kiedy będzie wiadomo, że
funkcjonalnie jest OK).

Zgodnie z wcześniejszymi ustaleniami, w tym commicie starałam się nie
wprowadzać upiększających zmian w istniejącym kodzie. Na przykład
pozostawiłam nazwy interfejsów *AsyncWrite* i *ReadNow*, ale w całkiem
nowych fragmentach kodu pojawia się *AsyncRead* zamiast *ReadNow*, bo taka
ma być nazwa docelowa.

On 21 Feb 2017 5:15 p.m., "Maciej Kisiel" <notifications@github.com> wrote:

> *@maciej-kisiel* commented on this pull request.
> ------------------------------
>
> In nesc/whip6/platforms/boards/cc26xxbased/BlockingUART0Pub.nc
> <https://github.com/InviNets/whip6-pub/pull/3#discussion_r102247668>:
>
> > @@ -15,11 +15,18 @@
>  #endif
>
>  configuration BlockingUART0Pub {
> +    provides interface BlockingRead<uint8_t>;
> +    provides interface ReadNow<uint8_t>;
>
> Zamieszczenie interfejsów asynchronicznych w konfiguracji o nazwie
> BlockingUART0Pub wydaje mi się trochę nieintuicyjne.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/InviNets/whip6-pub/pull/3#pullrequestreview-22998820>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXcynDKQddOHKD2z540aIRyhYmW_E9n-ks5rew2AgaJpZM4MA8h->
> .
>

2017-02-22 12:48 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncReadDemo/AsyncReadDemoPrv.nc
> +    uint8_t locVal;
Next time, prefix a module's local variables with "m_" (e.g., "m_locVal"). In this way, it is easier to navigate in the code.

2017-02-22 12:50 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncReadDemo/AsyncReadDemoPrv.nc
> +                atomic {
Remove "atomic", because the event is synchronous.

2017-02-22 12:50 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncReadDemo/AsyncReadDemoPrv.nc
> +                atomic {
Same here.

2017-02-22 12:53 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncReadDemo/build.spec
> +boards:
For safety, use only our platforms, that is, remove all the remaining ones.

2017-02-22 13:08 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncWriteDemo/README
> +3. Reset the board and observe both: the output printed in the minicom terminal and leds.
You may want to add a note, that the application is one shot. In order to test it again, one needs to reset the board again.

2017-02-22 13:25 UTC, konrad-iwanicki requested changes

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncWriteDemo/build.spec
> +app name: AsyncWriteDemoApp
Like before.

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/AsyncWriteDemo/AsyncWriteDemoPrv.nc
> +    uint8_t val;
Like before.

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/BlockingReadDemo/build.spec
> +app name: BlockingReadDemoApp
...

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/BlockingWriteDemo/BlockingWriteDemoPrv.nc
> +    uint8_t val;
...

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/BlockingReadDemo/BlockingReadDemoPrv.nc
> +   uint8_t val;
...

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/BlockingWriteDemo/BlockingWriteDemoPrv.nc
> +        } while (val != 'z' && result == SUCCESS);
Don't we want to signal an error with the red LED here?

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/apps/BlockingWriteDemo/build.spec
> +boards:
...

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/BlockingUART0Pub.nc
> +    provides interface ReadNow<uint8_t>;
Agreed. Why do we forward async interfaces in this configuration?

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTAsyncWritePrv.nc
> +    default async event void AsyncWrite.writeDone(error_t result) { }
This module provides only a single interface. Why do you want a default event handler?

2017-02-22 13:25 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTReadNowPrv.nc
> +    default async event void ReadNow.readDone(error_t result, uint8_t val) { }
Same here. Why do you want a default event handler in a module that provides only a single interface?

2017-02-27 11:24 UTC, IngaRueb commented on nesc/whip6/apps/BlockingWriteDemo/BlockingWriteDemoPrv.nc
> +        } while (val != 'z' && result == SUCCESS);
We might want to but it is not necessary - in case there is an error the alphabet will not be printed correctly.

2017-03-13 16:46 UTC, konrad-iwanicki approved these changes

2017-03-23 12:38 UTC, merged