Add transmit-only UART using Sensor Controller
InviNets/whip6-pub pull request #4
Opened 2017-02-22 15:37 UTC by maciej-kisiel

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/apps/SCIFUARTPrintf/SCIFUARTPrintfPrv.nc
> +        call Timer.startWithTimeoutFromNow(2048);
Is this 2048 ms ? It doesn't seem too demanding. Anyway, pls add comment with unit used here.

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#define SC_UART_BAUD_RATE 115200
Supervisor uses 57600 by default, and it's pretty hard to change (kernel console, uboot). Could we use that speed here as the default too?

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/PlatformSCIFUARTPrv.nc
> + * Copyright (c) University of Warsaw
Add year (2017), and in some more places too

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[16];
16 may not be enough for string you put in here.

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +            needed = strlen(m_buffer);
needed = sprintf(...) ?

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +                if (m_last_char != 0) {
What if the last printed characted was indeed '\0'? It seems like it loses any zero bytes, but maybe we're ok with this, though I think someone will try printing binary data this way.

2017-02-28 18:59 UTC, mdebski commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +        uint32_t free = 2 * (SCIF_UART_TX_FIFO_MAX_COUNT - scifUartGetTxFifoCount());
comment while *2 pls. In general, it would be nice to describe here briefly the thing about 16 words there being used.

2017-02-28 19:20 UTC, mdebski commented
It would be useful if you put the TI's original driver first in separate commit, then your changes, so we could take a look at it without reviewing TI's code.

2017-02-28 19:24 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#define SC_UART_BAUD_RATE 115200
Isn't our intention for it to be as fast as it can be?

2017-02-28 19:26 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[16];
You think we'll lose more than 10^7 bytes?

2017-02-28 19:27 UTC, mdebski commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[16];
I think we do not want buffer overflows whatever happens :p

2017-02-28 19:27 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +            needed = strlen(m_buffer);
Good point.

2017-02-28 19:27 UTC, mdebski commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#define SC_UART_BAUD_RATE 115200
Then why not 460000?

2017-02-28 19:31 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +                if (m_last_char != 0) {
I think we decided to not print zero characters. We use them to flush one character (scifUartTxPutOneChar(c) = scifUartTxPutTwoChars(c, 0))

2017-02-28 19:32 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[16];
Okay, will make it 20 then.

2017-02-28 19:34 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#define SC_UART_BAUD_RATE 115200
As fast as possible but with no errors.

2017-02-28 22:17 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/PlatformSCIFUARTPrv.nc
> + * Copyright (c) University of Warsaw
Done

2017-02-28 22:18 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[16];
Done

2017-02-28 22:20 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +        uint32_t free = 2 * (SCIF_UART_TX_FIFO_MAX_COUNT - scifUartGetTxFifoCount());
Done, I guess..

2017-02-28 22:20 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +            needed = strlen(m_buffer);
Done

2017-02-28 22:21 UTC, maciej-kisiel commented on nesc/whip6/apps/SCIFUARTPrintf/SCIFUARTPrintfPrv.nc
> +        call Timer.startWithTimeoutFromNow(2048);
Done

2017-03-01 18:14 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +            needed = strlen(m_buffer);
But no, it seems that this sprintf has a different signature than the one from cstdio.

2017-03-09 18:18 UTC, maciej-kisiel commented
New commits, the app are improved and the driver now waits for the buffer to have 1/4 of space free before resuming sending bytes.

2017-03-13 16:43 UTC, konrad-iwanicki requested changes
Next time, smaller commits, please. One commit at a time.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#ifndef SC_UART_BAUD_RATE
This type of ifdefs should not be within nc files.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#define SC_UART_BAUD_RATE 115200
So what is the final conclusion here?

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/PutcharProviderPub.nc
> -    // -- putchar over UART0
This should not be deleted but rather ifdefed. We may yet want to have a putchar provider over something else than the sensor controller.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/PlatformSCIFUARTPrv.nc
> +        panic("Spurious alert from Sensor Controller");
Ask Przemek Horban if it is safe to use panic in async code.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/sce_uart_emulator.lst
> +               .deffile adi_defs.asm
Why do we need this file?

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/scif_uart_emulator.c
> +/// \addtogroup module_scif_driver_setup
Is this file auto-generated?

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    char m_buffer[20]; // buffer to contain the message about lost bytes
No magic constants. Extract a constant.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +            sprintf(m_buffer, "\nLOST:%d\n%c", m_lost_bytes, value);
sprintf is unsafe. Use snprintf instead.

2017-03-13 16:43 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    uint32_t m_free_threshold = 2 * SCIF_UART_TX_FIFO_MAX_COUNT / 4;
Why is this a variable?

2017-03-13 18:38 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/scif_uart_emulator.c
> +/// \addtogroup module_scif_driver_setup
It is, I just changed one import.

2017-03-13 18:38 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/cherry-v1/scif_uart/sce_uart_emulator.lst
> +               .deffile adi_defs.asm
I thought it would be nice to have the source code for sensor controller at the same place. Can delete if that's not necessary.

2017-03-13 18:38 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/PutcharProviderPub.nc
> -    // -- putchar over UART0
Which one should be the default?

2017-03-13 18:38 UTC, maciej-kisiel commented on nesc/whip6/platforms/boards/cc26xxbased/NonBlockingSCUARTPub.nc
> +#ifndef SC_UART_BAUD_RATE
This file was based on BlockingUART0Pub.nc. How should it be done, then?

2017-03-28 19:03 UTC, maciej-kisiel commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    const uint32_t SC_UART_FREE_THRESHOLD = 2 * SCIF_UART_TX_FIFO_MAX_COUNT / 4; // == 1/4
Is it the right way to add a constant?

2017-04-06 11:05 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/uart/HalUARTNonBlockingWritePrv.nc
> +    const uint32_t SC_UART_FREE_THRESHOLD = 2 * SCIF_UART_TX_FIFO_MAX_COUNT / 4; // == 1/4
No, use an enum.

2017-04-06 11:06 UTC, merged