Added ICount.
InviNets/whip6-pub pull request #9
Opened 2017-06-16 19:58 UTC by xavrin

2017-06-18 14:21 UTC, konrad-iwanicki requested changes
Never use types with unknown widths.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/api/io/EventCount.nc
> +interface EventCount {
Parametrize this interface with a type.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/api/io/EventCount.nc
> +    command error_t read(unsigned long long *value);
Use a parametrized type here.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/api/io/EventCount.nc
> +    // Initialize all necessary hardware and start counting events.
Use JavaDoc/Doxygen-like comments.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/api/io/EventCountConfig.nc
> +interface EventCountConfig {
Is this interface really so generic that it should not have ICount in its name?

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +module ICountReadPrv {
ICountReadAppMainPrv

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/api/io/EventCount.nc
> +    command error_t read(unsigned long long *value);
Moreover, use a type with a known width, for example, uint64_t.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +    int timestamp;
Never use a type with an unknown width.

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +        unsigned long long ticks = 0;
uint64_t

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +            printf("ICount - number of ticks: %u, timestamp: %d\n",
%lu %llu

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/timers/HalEventCountPrv.nc
> +    unsigned long long evCnt[2] = {0};
uint64_t

2017-06-18 14:21 UTC, konrad-iwanicki commented on nesc/whip6/platforms/parts/mcu/cc26xx/timers/HalEventCountPrv.nc
> +    unsigned cachedTimer[2] = {0};
uint32_t

2017-06-19 19:49 UTC, xavrin commented on nesc/whip6/api/io/EventCountConfig.nc
> +interface EventCountConfig {
These EventCount/EventCountConfig interfaces together with HalEventCountPub can be used to count events on any pin. I felt it's generic enough to separate it from ICount.

2017-06-19 19:54 UTC, xavrin commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +module ICountReadPrv {
Hm, I followed naming convention used in all apps - suffix "App" for configuration and "Prv" for implementation.
Why should I add "AppMain" here?

2017-06-19 20:21 UTC, xavrin commented on nesc/whip6/apps/ICountRead/ICountReadPrv.nc
> +            printf("ICount - number of ticks: %u, timestamp: %d\n",
Currently printf implementation doesn't support these flags (%lu and %llu). See:
nesc/whip6/lib/extern/tfp_printf/cortex-m3/tfp_printf.c

2017-06-19 20:31 UTC, xavrin commented
I changed logic a bit to polling the counter value.
I had constant problems with dealing with overflow while using the interrupt approach.
Now it's a bit simpler and its correctness is obvious.

2017-06-21 19:39 UTC, merged